export const SHOW_PROGRESS_BAR = 'SHOW_PROGRESS_BAR';
export const APP_SHOW_MODAL = 'APP_SHOW_MODAL';
export const APP_BOOKINGS_SUCCESS = 'APP_BOOKINGS_SUCCESS';
export const APP_BOOKINGS_ERROR = 'APP_BOOKINGS_ERROR';